server:
  port: 9010
spring:
  application:
    name: oauth2-as-inmemory

security:
  oauth2:
    client:
      client-id: client_id
      client-secret: client_secret
      scope: app,web
      authorized-grant-types: authorization_code,refresh_token,password,implicit,client_credentials
      registered-redirect-uri: https://www.baidu.com
      access-token-validity-seconds: 7200
      refresh-token-validity-seconds: 720000