server:
  port: 9020

security:
  oauth2:
    client:
      client-id: client_id
      client-secret: client_secret
      user-authorization-uri: http://localhost:9010/oauth/authorize
      access-token-uri: http://localhost:9010/oauth/token
    resource:
      token-info-uri: http://localhost:9010/oauth/check_token
